kotlin.code.style=official

diskordVersion=1.7.3
kotlinxCoroutinesVersion=1.5.0
kotlinSerializationVersion=1.2.1
ktorVersion=1.6.0
exposedVersion=0.22.1
slf4jVersion=1.7.26
commonsIoVersion=2.6
kotlinLoggingVersion=1.7.8
guavaVersion=28.2-jre
h2Version=1.4.200
jodaTimeVersion=2.10.5
kordVersion=0.7.3