[versions]
buildconfig = "6.0.9" # https://plugins.gradle.org/plugin/com.github.gmazzo.buildconfig
commons-io = "2.21.0" # https://central.sonatype.com/artifact/commons-io/commons-io
exposed = "1.3.0" # https://central.sonatype.com/artifact/org.jetbrains.exposed/exposed-dao/
flyway = "12.1.0" # https://central.sonatype.com/artifact/org.flywaydb/flyway-core/
git-version = "5.0.0" # https://plugins.gradle.org/plugin/com.palantir.git-version
guava = "33.6.0-jre" # https://central.sonatype.com/artifact/com.google.guava/guav
h2 = "2.4.240" # https://central.sonatype.com/artifact/com.h2database/h2/
hikari-cp = "7.0.2" # https://central.sonatype.com/artifact/com.zaxxer/HikariCP/a
kodein = "7.32.0" # https://central.sonatype.com/artifact/org.kodein.di/kodein-di/
kord = "0.18.1" # https://central.sonatype.com/artifact/dev.kord/kord-core/
kotlin = "2.3.21" # https://central.sonatype.com/artifact/org.jetbrains.kotlin/kotlin-stdlib-jdk8/
kotlin-logging = "8.0.4" # https://central.sonatype.com/artifact/io.github.oshai/kotlin-logging
ktor = "3.4.3" # https://central.sonatype.com/artifact/io.ktor/ktor-client-cio/
logback = "1.5.33" # https://central.sonatype.com/artifact/ch.qos.logback/logback-classic/
sentry = "8.43.0" # https://search.maven.org/artifact/io.sentry/sentry/
shadow = "9.4.2" # https://plugins.gradle.org/plugin/com.gradleup.shadow

[libraries]
apache-commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
exposed-migration-jdbc = { module = "org.jetbrains.exposed:exposed-migration-jdbc", version.ref = "exposed" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
flyway = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari-cp" }
kodein-di = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }
kord = { module = "dev.kord:kord-core", version.ref = "kord" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
sentry = { module = "io.sentry:sentry", version.ref = "sentry" } # https://docs.gitlab.com/ee/operations/error_tracking.html#integrated-error-tracking
sentry-extensions-kotlin = { module = "io.sentry:sentry-kotlin-extensions", version.ref = "sentry" }
sentry-exrensions-jdbc = { module = "io.sentry:sentry-jdbc", version.ref = "sentry" }

[bundles]
common = [ "kotlin-stdlib", "ktor-client-core", "ktor-client-cio", "kord" ]
database = [ "exposed-dao", "exposed-jdbc", "exposed-kotlin-datetime", "exposed-migration-jdbc", "hikari-cp", "flyway" ]
sentry-kotlin = [ "sentry", "sentry-extensions-kotlin" ]
sentry-jdbc = [ "sentry", "sentry-exrensions-jdbc" ]

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
git-version = { id = "com.palantir.git-version", version.ref = "git-version" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
